# Generated by Django 5.0 on 2024-02-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
